version: '3'

services:
  spark:
    image: xsilady/my_spark
    hostname: sparkmaster
    container_name: sparkmaster
    # command: ["cd", "/data", "&&", "jupyter", "notebook", "--ip",  "0.0.0.0", "--allow-root"]
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PID_DIR=/myTemp
      - SPARK_LOCAL_DIRS=/myTemp
    ports:
      - '8080:8080'
      - '8888:8888'
      - '4040:4040'
    volumes:
    # TODO: change mounts to correct folders
      - ./data/:/data
      - ./docker-tmp-volumes/master:/myTemp
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
  spark-worker-1:
    image: xsilady/my_spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PID_DIR=/myTemp
      - SPARK_LOCAL_DIRS=/myTemp
    volumes:
    # TODO: change mounts to correct folders
      - ./data/:/data
      - ./docker-tmp-volumes/worker1:/myTemp
  spark-worker-2:
    image: xsilady/my_spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=8G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_PID_DIR=/myTemp
      - SPARK_LOCAL_DIRS=/myTemp
    volumes:
    # TODO: change mounts to correct folders
      - ./data/:/data
      - ./docker-tmp-volumes/worker2:/myTemp

